### ISSUE TITLE
Example for Ling.Audit?

### ISSUE THREAD

**Issue by ignatandrei** [ling921/dotnet-lib#14]
I maintain a list of Roslyn Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG
I wish to add Ling.Audit 
Could you make a simple console application to show its usage ?
Thanks
Andrei

**Comment by ling921** [comment]
I updated README file, please check [https://github.com/ling921/dotnet-lib/blob/master/src/Ling.Audit/README.md](https://github.com/ling921/dotnet-lib/blob/master/src/Ling.Audit/README.md)

**Comment by ignatandrei** [comment]
https://ignatandrei.github.io/RSCG_Examples/v2/docs/Ling.Audit 

Thanks for your time!
Andrei
